### ISSUE TITLE
What commands were used to strip the binaries?

### ISSUE THREAD

**Issue by jupiterepoch** [CUMLSec/XDA#3]
Hello, I'm hoping to use your pretrained weights, which makes it very important for me to keep my binaries the same format as yours. Do you mind divulging the exact commands you used to strip the binaries? (both ELF and .exe versions) Thanks!

**Comment by peikexin9** [comment]
Hi @jupiterepoch, thanks for your interest! We do not explicitly strip the binaries as we can just take the bytes from the <.text> section and train the model to detect function boundaries. You can take a look at the data format at https://github.com/CUMLSec/XDA/tree/main/data-src/funcbound, which includes the training/testing samples.

**Comment by jupiterepoch** [comment]
Thank you!
